const { TAX_RATES, SHIPPING, DISCOUNT_TYPES, SAMPLE_COUPONS } = require('./utils/constants');
const { roundToTwo, validateCoupon } = require('./utils/validators');
class PricingEngine {
  constructor(couponsDb = SAMPLE_COUPONS) { this.coupons = { ...couponsDb }; }
  calculateItemTax(price, quantity, category = 'default') { if (typeof price !== 'number' || price < 0) throw new Error('Price must be a non-negative number'); if (typeof quantity !== 'number' || quantity < 0) throw new Error('Quantity must be a non-negative number'); const rate = TAX_RATES[category] || TAX_RATES.default; return roundToTwo(price * quantity * rate); }
  calculateTotalTax(cartItems) { if (!Array.isArray(cartItems)) throw new Error('Cart items must be an array'); return roundToTwo(cartItems.reduce((sum, item) => sum + this.calculateItemTax(item.price, item.quantity, item.category), 0)); }
  calculateShipping(subtotal, shippingType = 'standard') { if (typeof subtotal !== 'number' || subtotal < 0) throw new Error('Subtotal must be a non-negative number'); const validTypes = ['standard', 'express']; if (!validTypes.includes(shippingType)) throw new Error('Invalid shipping type. Use: ' + validTypes.join(', ')); if (shippingType === 'standard' && subtotal >= SHIPPING.FREE_THRESHOLD) return 0; return shippingType === 'express' ? SHIPPING.EXPRESS_COST : SHIPPING.STANDARD_COST; }
  applyPercentageDiscount(amount, percentage) { if (typeof amount !== 'number' || amount < 0) throw new Error('Amount must be a non-negative number'); if (typeof percentage !== 'number' || percentage < 0 || percentage > 100) throw new Error('Percentage must be between 0 and 100'); return roundToTwo(amount * (percentage / 100)); }
  applyFixedDiscount(amount, discountValue) { if (typeof amount !== 'number' || amount < 0) throw new Error('Amount must be a non-negative number'); if (typeof discountValue !== 'number' || discountValue < 0) throw new Error('Discount value must be a non-negative number'); return roundToTwo(Math.min(discountValue, amount)); }
  getCoupon(code) { if (!code || typeof code !== 'string') throw new Error('Coupon code must be a non-empty string'); const coupon = this.coupons[code.toUpperCase()]; const validation = validateCoupon(coupon); if (!validation.valid) throw new Error(validation.reason); return coupon; }
  applyCoupon(code, subtotal) { const coupon = this.getCoupon(code); if (subtotal < coupon.minOrderValue) throw new Error('Minimum order value for this coupon is ' + coupon.minOrderValue + '. Current subtotal: ' + subtotal); switch (coupon.type) { case DISCOUNT_TYPES.PERCENTAGE: return this.applyPercentageDiscount(subtotal, coupon.value); case DISCOUNT_TYPES.FIXED: return this.applyFixedDiscount(subtotal, coupon.value); default: throw new Error('Unsupported coupon type: ' + coupon.type); } }
}
module.exports = PricingEngine;
